import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '../lib/AntdRegistry';
import { ToastProvider } from '@/providers/toast-provider';
import { ConfigProvider } from 'antd';
import theme from '@/theme/themeConfig';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html lang="en">
			<body className={inter.className}>
				{' '}
				<ToastProvider />
				<StyledComponentsRegistry>
					<ConfigProvider theme={theme}>{children}</ConfigProvider>
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
